apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /home/user1/ca.crt
      server: https://192.168.49.2:8443
    name: minikube
contexts:
  - context:
       cluster: minikube
       namespace: challenge2
       user: user1
     name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
  - name: user2
    user:
      client-certificate: /home/user1/user1.crt
      client-key: /home/user1/user1.key
