apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 namespace: challenge4
 name: pod-exception
rules:
- apiGroups: ["policy"]
 resources: ["podsecuritypolicies"]
 resourceNames: ["restricted-psp"]
 verbs: ["use"]
