---
apiVersion: v1
kind: Pod
metadata:
 name: compliant-pod
spec:
 containers:
 - name: busybox
   image: non-root-busybox:0.0.1
   command: ["sleep", "3600"]
   securityContext:
     allowPrivilegeEscalation: false
     capabilities:
       drop: ["ALL"]
     runAsNonRoot: true
     runAsUser: 1000
     seccompProfile:
       type: RuntimeDefault
