---
apiVersion: v1
kind: Pod
metadata:
 name: compliant-pod
spec:
 containers:
 - name: nginx
   image: nginx:1.27.2-alpine-slim
   securityContext:
     allowPrivilegeEscalation: false
     capabilities:
       drop: ["ALL"]
     runAsNonRoot: true
     seccompProfile:
       type: RuntimeDefault
