---
apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /home/user2/.kube/ca.crt
      server: https://192.168.49.2:8443
    name: minikube
contexts:
  - context:
      cluster: minikube
      namespace: challenge2
      user: user2
    name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
  - name: user1
    user:
      client-certificate: /home/user2/.kube/user1.crt
      client-key: /home/user2/.kube/user1.key
