apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: allow-non-compliant
 namespace: challenge4
subjects:
- kind: ServiceAccount
 name: default
 namespace: challenge4
roleRef:
 kind: Role
 name: pod-exception
 apiGroup: rbac.authorization.k8s.io
